### ISSUE TITLE
Please consider making all files installed by the header-only version different from files installed by the library version

### ISSUE THREAD

**Issue by yurivict** [cschreib/snitch#125]
Currently the file ```lib/cmake/snitch/snitch-config.cmake``` is installed by both.

In FreeBSD we would like to be able to install both flavors simultaneously, but these flavors conflict on this file.

Maybe it can be removed into ```lib/cmake/snitch/snitch-header-only-config.cmake``` ?

**Comment by tocic** [comment]
There are the same. You can check that by running `diff` on them.

**Comment by yurivict** [comment]
But they still conflict because two different packages install the same file.

**Comment by tocic** [comment]
Which tool says that there are in conflict? I mean `cmake --install` just overwrites the file and since there are identical there's no problem in that.

**Comment by yurivict** [comment]
FreeBSD's ```pkg install snitch-testing-headers-only``` complains that it conflicts with ```snitch-testing``` and can't be installed.

In general packages can't overwrite each other's files.

cmake of course overwrites files because it is a build tool, not a packaging tool.

**Comment by tocic** [comment]
If there are 2 packages then I agree. I've just packaged them in [one](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=snitch).

**Comment by yurivict** [comment]
But then both flavors would be installed all the time.

**Comment by cschreib** [comment]
Hi both, and thanks for reporting this. @tocic is correct, the file is the same in both cases, and that is on purpose, so one can install multiple builds of snitch together and be found as `snitch`. 

If I make the file name different in both builds, the one cannot do 
```cmake
find_package(snitch CONFIG)
```

... and get both the `snitch::snitch` and `snitch::header-only` targets at once. That is because CMake `find_package(X)` looks for `X-config.cmake`; if the file name is different, then the `find_package` call will be different, e.g. `find_package(snitch-header-only)`.

That's possible, but not really how things are normally done in CMake, so I would expect people would find it surprising. I don't know how other packages handle this, but see e.g. Boost and SFML; they both are a single "library" with multiple "components" that can be installed separately. Perhaps the same packaging solution can be reused here?

**Comment by cschreib** [comment]
I don't use FreeBSD so please bear with me, but from what I can tell from the FreeBSD ports, the two examples I gave above (SFML and Boost) are each packaged as a single master package ([`sfml`](https://cgit.freebsd.org/ports/tree/devel/sfml) and [`boost-libs`](https://cgit.freebsd.org/ports/tree/devel/boost-libs)) rather than multiple packages where each sub-library can be installed separately. 

Based on this, my suggestion would be indeed to always package the compiled and header-only versions together. You could also make one dependent on the other, so the dependent package would not install the root config file, but that seems a bit arbitrary to me.

**Comment by yurivict** [comment]
I've made them into flavors for now on FreeBSD.
Maybe will merge them later, but that would be more work.

**Comment by cschreib** [comment]
I will close this issue if this resolved, but feel free to re-open if you want to discuss this further. Thank you for the feedback!
