### ISSUE TITLE
snitch doesn't compile

### ISSUE THREAD

**Issue by s9w** [cschreib/snitch#129]
context: 1.2.2 release, header-only mode, newest VS (17.8.0 preview 2)

Even compiling a trivial

```c++
#define SNITCH_IMPLEMENTATION
#include <snitch/snitch_all.hpp>

TEST_CASE("Factorials are computed", "[factorial]") {
   REQUIRE(true);
}
```

results in `error C2397: conversion from 'long' to 'size_t' requires a narrowing conversion`

**Comment by s9w** [comment]
I think I nailed it down to [this line](https://github.com/cschreib/snitch/blob/main/include/snitch/snitch_macros_check_base.hpp#L29), specifically the `__LINE__` macro. That might need a cast or something.

**Comment by cschreib** [comment]
Thanks for reporting this, and indeed that was my suspicion as well. A cast in the macro should fix it. Feel free to open a PR, otherwise I will do it tomorrow or this weekend.

**Comment by cschreib** [comment]
A neater alternative would be to use `std::source_location`, but I was worried of the potential compilation time overhead. Perhaps unjustifiably so since I never measured it.

**Comment by s9w** [comment]
This was probably more or less the place for which `std::source_location` was intended, so I'd give it a go yeah.

**Comment by cschreib** [comment]
https://github.com/cschreib/snitch/pull/130/commits/a7d9e462ba30dcb4d638fda3eb4be35de34f74b4 should fix the problem, if you get a chance to test it.

I'm refraining from using `std::source_location` for now. Its main advantage is that it doesn't require macros, but since *snitch* checks are macro-based, this isn't something we really benefit from. It would just create overhead, since eventually we want to store a `{std::string_view, std::size_t}`, that it would need converting into. It will be more useful when reflection comes in and can decompose expressions without macros, then *snitch* can become mostly macro-free. But we're not there yet!

**Comment by s9w** [comment]
So many things will get easier with reflections :<. I'll test tomorrow,
thanks.

**Comment by cschreib** [comment]
Merged and released; I assumed all went fine :)
