### ISSUE TITLE
Latest release does not provide snatch_all.hpp?

### ISSUE THREAD

**Issue by horenmar** [cschreib/snitch#41]
Quote from readme:

> For extra convenience, snatch is also provided as a header-only library. The main header is called snatch_all.hpp, and can be downloaded as an artifact from each release on GitHub.

I don't see the convenience header attached to the releases.

**Comment by cschreib** [comment]
Hi an thanks for your feedback. This is a quote from the readme for the `main` branch, which is not yet released. There has been no release since `snatch_all.hpp` was added. The next release will be v1.0; I am cleaning up a few last issues, but it should be available shortly.

I will leave this issue open to remind me to double-check that the release has the right artifacts attached to it.

**Comment by horenmar** [comment]
Ok, sounds fine.

**Comment by cschreib** [comment]
v1.0.0 is out, and the header-only version is included there as an artifact in `snitch-header-only.zip`. I'll close this issue, but feel free to comment if that's not working for you.
