### ISSUE TITLE
Check your code with werror and wpedantic

### ISSUE THREAD

**Issue by victimsnino** [cschreib/snitch#77]
Hey! Thank you for this amazing testing framework. Currently I’m trying to add it to my library, but CI gets a bunch of error on your library due to werror and wpedantic flags

for example
Error: /home/runner/work/ReactivePlusPlus/ReactivePlusPlus/build/_deps/snitch-src/src/snitch.cpp:76:55: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
[60](https://github.com/victimsnino/ReactivePlusPlus/actions/runs/4536738324/jobs/7993786545#step:4:63)
      const int return_code = std::snprintf(nullptr, 0, get_format_code<T>(), value);
      
   
 Or some stupid one

 Error: /home/runner/work/ReactivePlusPlus/ReactivePlusPlus/build/_deps/snitch-src/include/snitch/snitch.hpp:1151:2: error: extra ‘;’ [-Werror=pedantic]
[66](https://github.com/victimsnino/ReactivePlusPlus/actions/runs/4536738324/jobs/7993788231#step:5:69)
   1151 | }; // namespace event  

Full run can be found there: https://github.com/victimsnino/ReactivePlusPlus/actions/runs/4536738324

I could find workaround, but anyway it is better for you to have zero warnings even on most aggressive level :)

**Comment by cschreib** [comment]
Hi there and thank you for the bug report. I am a bit confused as to why I am not catching these warnings, because I do compile the code with `-Wall -Wextra -Werror`. I don't use `-pedantic`, but I just tried adding it to the compilation options, and I am still not getting the warnings you are seeing. In case it was something wrong with my CMake scripts, I just copied `snitch_all.hpp` into [Godbolt](https://godbolt.org/z/cP1bnsPY7) and explicitly set these warning levels, both with the latest clang and gcc; still no error.

Are you using a specific compiler version, and/or a specific platform? Or perhaps some additional compilation options. Are you able to create a minimal example I can reproduce, outside of your CI scripts? Having the full compilation command would also help.

At any rate, the warning about the extra semicolon is genuine, and I will fix it. The other warning is noise; I may be able to find an alternative implementation that does not trigger it, but that first requires me being able to reproduce it.

**Comment by victimsnino** [comment]
I'm catching these errors during linking against `snitch::snitch` target, not header-only version. Most of the errors came from `snitch.cpp` file. Try this one. If you still can't reproduce, i would try to prepare example

**Comment by cschreib** [comment]
```
g++-10 -std=c++20 -Wall -Wextra -Werror -pedantic snitch.cpp -o snitch.o -I ../include -I ../build/
```

Still nothing :shrug:

**Comment by victimsnino** [comment]
yeah, sure, not problem. It is not blocker for me, just wanted to notify you about _possible_ issue :). In this case I would suggest you to add (or at least, to mention)
```cmake
target_compile_options(snitch PRIVATE "-w")
```
as part of the "installation guide"
